# Generated by Django 5.0 on 2023-12-24 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_mybooks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mybooks',
            new_name='Mybook',
        ),
    ]
