# Generated by Django 5.0 on 2024-02-02 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer',
        ),
    ]
