# Generated by Django 5.0 on 2024-04-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_country_order_orderitems_ordertracking_state_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='orderdate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
