# Generated by Django 5.0 on 2024-04-01 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_alter_orderitems_orderdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='orderdate',
            new_name='order_date',
        ),
    ]
