# Generated by Django 5.0 on 2024-04-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybook',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
